- name: configure backend server
  hosts: backend
  become: yes
  tasks:
  - name: disable nodejs 18
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable nodejs 20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.command:
      name: nodejs
      state: present

  - name: Create a user expense
    ansible.builtin.user:
    name: expense
   # create_home: yes